Update patch set 5
Patch Set 5:

When timestamp is formatted '158168661.2215465' (seconds in this way)  instead of '1581686612215.465' the following error occurs



Traceback (most recent call last):                                                                          │
│  File "/opt/stack/monasca-persister/monasca_persister/repositories/persister.py", line 56, in _flush       │
│    self.repository.write_batch(self._data_points)                                                          │
│  File "/opt/stack/monasca-persister/monasca_persister/repositories/influxdb/abstract_repository.py", line 3│
│    self._influxdb_client.write_points(data_points, 'ms', protocol='line')                                  │
│  File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 483, in write_points               │
│    tags=tags, protocol=protocol)                                                                           │
│  File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 544, in _write_points              │
│    protocol=protocol                                                                                       │
│  File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 327, in write                      │
│    headers=headers                                                                                         │
│  File "/usr/local/lib/python3.6/dist-packages/influxdb/client.py", line 286, in request                    │
│    raise InfluxDBClientError(response.content, response.status_code)                                       │
│influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: points beyond retention policy droppe│
│                                                                                                            │
│                                                                                                            │
│During handling of the above exception, another exception occurred:                                         │
│                                                                                                            │
│Traceback (most recent call last):                                                                          │
│  File "/opt/stack/monasca-persister/monasca_persister/repositories/persister.py", line 85, in run          │
│    self._flush()                                                                                           │
│  File "/opt/stack/monasca-persister/monasca_persister/repositories/persister.py", line 64, in _flush       │
│    if "partial write: points beyond retention policy dropped" in ex.message:                               │
│AttributeError: 'InfluxDBClientError' object has no attribute 'message'

Patch-set: 5
Reviewer: Gerrit User 29909 <29909@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Verified=0